name: Workflow-with-norm-build-tests

on:
  push:
    branches: [ "evportel" ]
  pull_request:
    branches: [ "master" ]

jobs:

  norminette:
      name: norminette
      runs-on: ubuntu-20.04
      defaults:
        run:
          working-directory: .
      steps:
        - name: Checkout
          uses: actions/checkout@v3
  
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        
        - name: Install dependencies 
          run: |
            python -m pip install --upgrade pip setuptools
            python -m pip install norminette 
        
        - name: Test with norminette
          run: norminette
        
  build:
    name: build
    # needs: norminette
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3

      - name: make
        run: make

  Tester_Denis_Godoy:
    name: Tester Denis Godoy
    needs: build
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3

      - name: install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install valgrind -y

      - name: Cloning Tester Denis Godoy
        run: |
          git clone https://github.com/denisgodoy/pipex-tester
          cd pipex-tester
          export TERM=xterm-256color
          make
  
  Tester_Vfurmane:
    name: Tester Valentin Furmanek
    needs: build
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3

      - name: install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install valgrind -y

      - name: Cloning Tester Denis Godoy
        run: |
          git clone https://github.com/evertonportela/pipex-tester
          cd pipex-tester
          export TERM=xterm-256color
          ./run.sh